inputs:
  POETRY_DIRECTORY:
    description: "Optional path to a poetry project"
    required: false

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # pin@v4

    # Install Poetry.
    - uses: snok/install-poetry@d45b6d76012debf457ab49dffc7fb7b2efe8071d # pin@v1.3.3
      with:
        version: 1.2.2

    - name: Install default python dependencies
      run: poetry install
      working-directory: testsuite

    - name: Install additional specified python dependencies from poetry
      if: inputs.POETRY_DIRECTORY != ''
      run: poetry install
      working-directory: ${{ inputs.POETRY_DIRECTORY }}
