[tool.poetry]
name = "aptos_testsuite"
version = "0.1.0"
description = "Aptos E2E tests, including Forge"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
click = "^8.1.3"
psutil = "^5.9.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportUndefinedVariable = "none"
